### PR TITLE
ui & api. add databases details

### PR DESCRIPTION
**Pull request by federicoballarini**
Added databases details like DB size and logs size.
Fixed some vulnerabilities.

Refer to https://github.com/NethServer/dev/issues/6106

### CODE REVIEW

**Comment by federicoballarini** [comment]
@gsanchietti could you check if acorn and minimist security issues are solved for you? From log still remains one fix, but if I force it build doesn't work fine.

Databases details are as follow in Databases page:

image

If all is ok for you we can merge this PR and go to test.
Wait for your feedback.

**Review by gsanchietti — APPROVED** [review]
From a formal point of view, the `read` API should be an `execute` because it doesn't return a JSON output.

See https://nethserver.github.io/nethserver-cockpit/api_guidelines/#execute

**Comment by federicoballarini** [comment]
> From a formal point of view, the `read` API should be an `execute` because it doesn't return a JSON output.
> 
> See https://nethserver.github.io/nethserver-cockpit/api_guidelines/#execute

I only have to rename read file to execute and change it in the function?

**Comment by gsanchietti** [comment]
> I only have to rename read file to execute and change it in the function?

Yes, that should be enough

**Comment by federicoballarini** [comment]
> > I only have to rename read file to execute and change it in the function?
> 
> Yes, that should be enough

After that, is better to merge all commits or squash and merge?

**Comment by gsanchietti** [comment]
You could squash it with:
- ui & api. add databases details
- api. fix read permissions 

But it's not really needed. ;)

**Comment by federicoballarini** [comment]
Execute permissions wrong, damn Windows! :/
I proceed now with squash and merge.

**Pull request merged**
